site_name: Azure AI-102 Learning Path Cheat Sheets
site_url: https://sitename.example
theme:
    name: material
    icon:
        logo: material/microsoft-azure

    palette:
        - scheme: default
          primary: blue
          accent: indigo
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
        - scheme: slate
          primary: blue
          accent: indigo
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode

plugins:
    - exclude:
          glob:
              - "**exercise/*"
              - "*.py"
              - "*.png"
              - "*.jpg"
              - "*.jpeg"

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences
